apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: anand
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [worker,anand]
  nodeSelector:
    matchLabels:
            node-role.kubernetes.io/anand: ""
